name: dencendor

on:
  workflow_dispatch:
  push:

jobs:
  build-linux:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Copy and Install
      run: |
        git clone https://github.com/Deepshift/DeepCreamPy
        cd DeepCreamPy
        pip install -r requirements-gpu.txt
